#!/bin/bash

# Script to install config files using GNU Stow.
# This script is idempotent and can be run multiple times without causing issues.

STOW_ARGS="--verbose --dotfiles --target=$HOME"

STOW_PACKAGES="zshrc vim git"

for package in $STOW_PACKAGES; do
    stow $STOW_ARGS $package
done

stow --verbose --target=$HOME/Library/Application\ Support/Code/User vscode

# Top level symlinks need to be done manually.
HERE=`pwd`
DOT_CONFIG=$HOME/.config
mkdir -p $DOT_CONFIG
ln -fs $HERE/nvim $DOT_CONFIG

