#!/bin/bash

# Script to install config files using GNU Stow.
# This script is idempotent and can be run multiple times without causing issues.

STOW_ARGS="--verbose --dotfiles --target=$HOME"

STOW_PACKAGES="vim git tmux"

# Install HOME directory packages
for package in $STOW_PACKAGES; do
    stow $STOW_ARGS $package
done

# NOTE: For bash, just add "source ~/linux-conf/bash/dot-bashrc" to ~/.bashrc

# Install custom location packages
stow --verbose --target=$HOME/.config/Code/User vscode

# Top level symlinks need to be done manually.
HERE=`pwd`
DOT_CONFIG=$HOME/.config
mkdir -p $DOT_CONFIG
ln -fs $HERE/nvim $DOT_CONFIG

source ~/.bashrc

