#!/bin/bash

# Script to install config files using GNU Stow.
# This script is idempotent and can be run multiple times without causing issues.

STOW_ARGS="--verbose --dotfiles --target=$HOME"

STOW_PACKAGES="vim git tmux nvim ghostty zed vscode"

for package in $STOW_PACKAGES; do
    stow $STOW_ARGS $package
done

source ~/.bashrc

